server:
  port: 8050
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: http://localhost:32769/ezhang/springcloud-study.git
          search-paths: cloud-repo
          username:
          password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-peer1:8761/eureka/,http://discovery-peer2:8762/eureka