spring:
  application:
    name: microservice-api-gateway
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-peer1:8761/eureka/,http://discovery-peer2:8762/eureka
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
#zuul:
#  ignored-services: microservice-provider-product          # 需要忽视的服务(配置后将不会被路由)
#  routes:
#    user:                                              # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
#      path: /user/**                                   # 想要映射到的路径
#      service-id: microservice-provider-user          # Eureka中的serviceId