
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: discovery-peer1
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://discovery-peer2:8762/eureka/
  server:
    enable-self-preservation: false   # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 6000    # 清理间隔（单位毫秒，默认是60*1000）

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: discovery-peer2
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://discovery-peer1:8761/eureka/

  server:
    enable-self-preservation: false   # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 6000    # 清理间隔（单位毫秒，默认是60*1000）